#travis file to run docker-compose
sudo: required

language: java

services:
  - docker

install:
  - mvn install -Dmaven.javadoc.skip=true -B -V

after_success:
  - docker-compose up --abort-on-container-exit

script:
  - mvn test