#travis file to run docker-compose
sudo: required

language: java

services:
  - docker

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - docker-compose up --abort-on-container-exit

before_script:
  - mvn clean

script:
  - mvn -Dtest=MyTest test