#travis file to run docker-compose
sudo: required

language: java

services:
  - docker

install:
  - docker build -t database db/.
  - docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - docker-compose up --abort-on-container-exit
  - mvn test -Dtest=com.napier.sem.MyTest
