#travis file to run docker-compose
sudo: required

language: java

services:
  - docker

after_success:
  - docker-compose up --abort-on-container-exit

before_script:
  - mvn clean

script:
  - mvn test -Dtest=MyTest