# docker-compose file to build/run containers
version: '3'
services:
  # OpenJDK Dockerfile is in same folder which is .
  app:
    build: .
    container_name: app1

  # MySQL is is MySQL folder
  db:
    build: MySQL/.
    container_name: mysql1
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  # PhpMyAdmin Docker container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=phpmyadmin.io
      - PMA_USER=user
      - PMA_PASSWORD=example